"""Produce the recorded punchline the page falls back to.

    # in one shell
    REDIS_URL=redis://localhost:6379/13 PYTHONPATH=src \\
        python -m uvicorn web.api:app --port 8000
    # in another
    PYTHONPATH=src python -m web.record_punchline

Committed output, regenerated by running it -- not hand-written. A fallback
that drifts from the code keeps showing numbers nobody produced.

**It drives `/api/race/run`, the same endpoint the page does.** A recording
produced by a different mechanism than the live demo is a number no live run
reproduces, which is worse than having no recording at all.

The file carries the timestamp, the Redis version and the URL it was recorded
against, and the page displays them, so a recording reads as a recording.
"""

from __future__ import annotations

import asyncio
import json
import os
import pathlib
from datetime import datetime, timezone

import httpx

OUT = pathlib.Path(__file__).resolve().parent / "punchline_recording.json"
TARGET = os.environ.get("RACE_URL", "http://127.0.0.1:8000")


async def main() -> int:
    """Record one real run, driven exactly the way the page drives one."""
    async with httpx.AsyncClient(base_url=TARGET, timeout=120) as client:
        body = (await client.post("/api/race/run")).json()
        if not body.get("live"):
            print(f"  {TARGET} refused a run (reason: {body.get('reason')}).")
            print("  Start the server with REDIS_URL set and try again.")
            return 1

        redis_version = "unknown"
        if url := os.environ.get("REDIS_URL"):
            import redis.asyncio as redis
            r = redis.from_url(url)
            redis_version = (await r.info("server")).get("redis_version", "unknown")
            await r.aclose()

    naive, lua = body["variants"]["naive"], body["variants"]["lua"]
    limit = body["limit"]
    record = {
        "recorded_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "redis_version": redis_version,
        "recorded_against": TARGET,
        "concurrency": naive["fired"],
        "limit": limit,
        "instances": naive["instances"],
        "spread_ms": naive["spread_ms"],
        "rtt_ms": naive["rtt_ms"],
        "naive": naive["allowed"],
        "lua": lua["allowed"],
        "naive_admitted": naive["admitted"],
        "lua_admitted": lua["admitted"],
    }

    print(f"  naive  {record['naive_admitted']:>3} of {record['concurrency']} "
          f"admitted against a limit of {limit}")
    print(f"  atomic {record['lua_admitted']:>3} of {record['concurrency']}")
    print(f"  served by {naive['instances']} instance(s), spread "
          f"{naive['spread_ms']}ms, round trip {naive['rtt_ms']}ms")

    # Validate before writing: overwriting a good recording with a degenerate
    # one replaces the evidence with its absence.
    if record["lua_admitted"] != limit:
        print("  REFUSING: the atomic limiter did not hold exactly to its limit")
        return 1
    if record["naive_admitted"] <= limit:
        # If the control stops over-admitting, no race occurred, and the
        # recording would show two limiters agreeing -- which proves nothing.
        print("  REFUSING: the naive control did not over-admit; no race occurred")
        return 1

    OUT.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print(f"  -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
