"""Produce the recorded punchline the page falls back to.

    # in one shell
    REDIS_URL=redis://localhost:6379/13 PYTHONPATH=src \\
        python -m uvicorn web.api:app --port 8000
    # in another
    PYTHONPATH=src python -m web.record_punchline

Committed output, regenerated by running it -- not hand-written. A fallback
that drifts from the code keeps showing numbers nobody produced.

**It drives the live HTTP path, not an in-process `asyncio.gather`.** That is
not a detail. Fifty coroutines gathered in one process overlap almost totally
and the naive limiter admits all fifty; fifty real HTTP requests overlap only
partly, because some genuinely arrive after earlier ones have written, and it
admits fewer. Both are races and both prove the point, but they are different
numbers -- and a recording produced one way, shown as the fallback for a demo
that runs the other way, would be a number no live run reproduces.

The file carries the timestamp, the Redis version and the URL it was recorded
against, and the page displays them, so a recording reads as a recording.
"""

from __future__ import annotations

import asyncio
import json
import os
import pathlib
from datetime import datetime, timezone

import httpx

OUT = pathlib.Path(__file__).resolve().parent / "punchline_recording.json"
TARGET = os.environ.get("RACE_URL", "http://127.0.0.1:8000")


async def fire_all(client: httpx.AsyncClient, start: dict, variant: str) -> list[bool]:
    query = {"run": start["run"], "exp": start["exp"], "start": start["start"],
             "token": start["token"], "variant": variant}
    responses = await asyncio.gather(
        *(client.get("/api/race/fire", params=query)
          for _ in range(start["concurrency"]))
    )
    return [r.json()["allowed"] for r in responses]


async def main() -> int:
    async with httpx.AsyncClient(base_url=TARGET, timeout=60) as client:
        start = (await client.post("/api/race/start")).json()
        if not start.get("live"):
            print(f"  {TARGET} has no live Redis (reason: {start.get('reason')}).")
            print("  Start the server with REDIS_URL set and try again.")
            return 1

        # Both volleys wait on the barrier the server issued, so the recording
        # captures the same synchronised race a visitor triggers.
        naive = await fire_all(client, start, "naive")
        lua = await fire_all(client, start, "lua")

        redis_version = "unknown"
        if url := os.environ.get("REDIS_URL"):
            import redis.asyncio as redis
            r = redis.from_url(url)
            redis_version = (await r.info("server")).get("redis_version", "unknown")
            await r.aclose()

    concurrency, limit = start["concurrency"], start["limit"]
    record = {
        "recorded_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "redis_version": redis_version,
        "recorded_against": TARGET,
        "concurrency": concurrency,
        "limit": limit,
        "naive": naive,
        "lua": lua,
        "naive_admitted": sum(naive),
        "lua_admitted": sum(lua),
    }

    print(f"  naive GET/SET  {record['naive_admitted']:>3} of {concurrency} "
          f"admitted against a limit of {limit}")
    print(f"  Lua (atomic)   {record['lua_admitted']:>3} of {concurrency}")

    # Validate before writing: overwriting a good recording with a degenerate
    # one replaces the evidence with its absence.
    if record["lua_admitted"] != limit:
        print("  REFUSING: the Lua limiter did not hold exactly to its limit")
        return 1
    if record["naive_admitted"] <= limit:
        # If the control stops over-admitting, no race occurred, and the
        # recording would show two limiters agreeing -- which proves nothing.
        print("  REFUSING: the naive control did not over-admit; no race occurred")
        return 1

    OUT.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    print(f"  -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
